#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output DP-2 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1920x1080 --rotate left --left-of DP-2

bspc monitor DP-2  	 1 2 3 4 
bspc monitor HDMI-1	 5 6 7 8

bspc config border_width        2
bspc config window_gap          8


bspc config normal_border_color		"#000000"
bspc config focused_border_color	"#FFFFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-scale $HOME/Pictures/car.jpg &
picom &
